---
deployment:
  tasks:
    - export DEPLOYPATH=/home/psyhohelpb/public_html/
    - export REPOPATH=/home/psyhohelpb/repositories/psycho/
    - /bin/rsync -aP --exclude '.git' --exclude '.well-known' ${REPOPATH}/ ${DEPLOYPATH} --delete-after
    - /bin/chmod -R 755 ${DEPLOYPATH}